[package]
name = "whitespace"
license = "MIT"
description = "Encode arbitrary data whitespaces and vice versa."
repository = "https://github.com/j-brn/whitespace-rs"
version = "2.0.0"
authors = ["Jonas <me@jbrn.eu>"]
edition = "2018"

[dependencies]
thiserror = "1.0"