[package]
name = "whitespace"
license = "MIT"
description = "Encode arbitrary data into tabs and whitespaces and vice versa."
repository = "https://github.com/j-brn/whitespace-rs"
version = "1.0.0"
authors = ["Jonas <me@jbrn.eu>"]
edition = "2018"

[dependencies]
